#!/bin/sh

# Template Judul Program
echo ""
echo "==========================================================="
echo "SELAMAT DATANG SYSADMIN, RAFI RASENDRYA FAVIAN - 2106751581"
echo "==========================================================="
time=$(date)
echo "$time"
echo ""

# Fungsi untuk kembali ke menu utama
backtomenu(){
	read -p "Kembali ke menu? [y/n] : " answermenu
	if [ $answermenu = "y" ]
	then
		mainmenu
	elif [ $answermenu = "n" ]
	then
		exit 1
	else
		read -p "Input tidak valid, silahkan input ulang [y/n]" answerinvalid
		if [ $answerinvalid = "y" ]
		then
			mainmenu
		elif [ $answerinvalid = "n" ]
		then
			exit 1
		else
			handleinvalid
		fi
	fi 
}

# Fungsi untuk handle invalid respon
handleinvalid(){
	read -p "Input tidak valid, silahkan input ulang [y/n]" answerinvalid
	if [ $answerinvalid = "y" ]
	then
		mainmenu
	elif [ $answerinvalid = "n" ]
	then
		exit 1
	else
		handleinvalid
	fi
}

# Fungsi Menu Utama
mainmenu(){
	echo ""
	echo "MENU INFORMASI:"
	echo "==============="
	echo ""
	echo "1. Informasi Sistem"
	echo "2. Status CPU"
	echo "3. Status Memori"
	echo "4. Status Disk"
	echo "5. Login User Terakhir"
	echo "6. Berita Keamanan Kernel dari packetstormsecurity.com"
	echo "7. Keluar"
	echo ""
	
	flag=true			# Buat flag untuk handle pilihan nomor
	
	while [ $flag = true ]
	do
		read -p "Pilihan nomor [1-7]: " command
		
		# Informasi Sistem
		if [ $command = 1 ]
		then
			echo ""
			echo "INFORMASI SISTEM"
			echo "================"
			echo ""
			echo "CPU Info"
			echo "--------"
			modelcpu=$(cat /proc/cpuinfo | grep 'model name' | cut -c 14-)
			corecpu=$(cat /proc/cpuinfo | grep 'cpu cores' | cut -c 13-)
			cachecpu=$(cat /proc/cpuinfo | grep 'cache size' | cut -c 14-)
			echo ""
			echo "Model CPU: $modelcpu" 
			echo "Jumlah Core: $corecpu"
			echo "Ukuran Cache: $cachecpu"
			echo ""
			echo "Sistem Info"
			echo "-----------"
			so=$(cat /etc/os-release | grep 'PRETTY_NAME' | cut -c 14-31)
			kr=$(uname -r)
			hn=$(hostname)
			ip=$(hostname -i)
			echo ""
			echo "Sistem Operasi: $so"
			echo "Kernel release: $kr"
			echo "Hostname: $hn"
			echo "IP: $ip"
			echo ""
			
			backtomenu
		
		# Status CPU
		elif [ $command = 2 ]
		then
			echo ""
			echo "STATUS CPU"
			echo "=========="
			echo ""
			echo "Daftar 5 proses teratas diurut berdasarkan utilisasi CPU:"
			utilisasicpu=$(ps -eo user,pid,%cpu,start,time,args --sort=-%cpu | head -6)
			echo ""
			echo "$utilisasicpu"
			echo ""
			echo ""
			
			backtomenu
			
		# Status Memori
		elif [ $command = 3 ]
		then
			echo ""
			echo "STATUS MEMORY"
			echo "============="
			echo ""
			echo "Memori Fisik:"
			sizememori=$(free | grep 'Mem' | cut -c 13-20)
			usedmemori=$(free | grep 'Mem' | cut -c 27-32)
			sisamemori=$(free | grep 'Mem' | cut -c 39-44)
			persenmemori=$(free -t | awk 'FNR == 2 {printf("%.2f"), $3/$2*100}')
			echo "Ukuran: $sizememori Kilobytes"
			echo "Digunakan: $usedmemori Kilobytes ($persenmemori %)"
			echo "Sisa (Free): $sisamemori Kilobytes"
			echo ""
			echo "Penyimpanan Swap:"
			sizeswap=$(free | grep 'Swap' | cut -c 13-20)
			usedswap=$(free | grep 'Swap' | cut -c 27-32)
			sisaswap=$(free | grep 'Swap' | cut -c 39-44)
			persenswap=$(free -t | awk 'FNR == 3 {printf("%.2f"), $3/$2*100}')
			echo "Ukuran: $sizeswap Kilobytes"
			echo "Digunakan: $usedswap Kilobytes ($persenswap %)"
			echo "Sisa (Free): $sisaswap Kilobytes"
			echo ""
			echo "Daftar 5 proses teratas diurut berdasarkan utilisasi memori:"
			echo ""
			utilisasimemori=$(ps -eo user,pid,%mem,start,time,args --sort=-%mem | head -6)
			echo "$utilisasimemori"
			echo ""
			echo ""
			
			backtomenu
		
		# Status Disk
		elif [ $command = 4 ]
		then
			echo ""
			echo "STATUS DISK"
			echo "==========="
			echo ""
			partisisize=$(df -h | head -n -4)
			directsize=$(du -h $HOME | tail -n 1)
			echo "Ukuran partisi (/)"
			echo "$partisisize"
			echo ""
			echo "Ukuran partisi (/home/rafifavian)"
			echo "$directsize"
			echo ""
			echo ""
			
			backtomenu
			
		# Login User Terakhir
		elif [ $command = 5 ]
		then
			echo ""
			echo "INFO LOGIN TERAKHIR"
			echo "==================="
			echo ""
			lastlogininfo=$(last | head -n 5)
			taillogininfo=$(last | tail -n 1)
			echo "USER     TTY             IP                      TIME"
			echo "$lastlogininfo"
			echo ""
			echo "$taillogininfo"
			echo ""
			
			backtomenu
			
		# Berita Keamanan Kernel dari packetstormsecurity.com
		elif [ $command = 6 ]
		then
			echo ""
			echo "Sedang mengambil data dari http://packetstormsecurity.com/..."
			echo ""
			sleep 1
			echo "BERITA KEAMANAN KERNEL TERBARU"
			echo "=============================="
			echo ""
			wget -q -O - http://rss.packetstormsecurity.com/files/tags/kernel/ | grep -E '(pubDate|description)' | head -10 | sed 's/<[^>]*>//g'
			echo ""
			
			backtomenu
			
		# Keluar	
		elif [ $command = 7 ]
		then
			echo ""
			echo "Sampai Jumpa dan Tetap Semangat!"
			echo ""
			exit 1
			
		
		# Input selain 1-7	
		else
			echo "Input tidak valid"
			echo ""
			continue
		fi
	done		
}

mainmenu
